config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  devise_for :users
  resources :users do
    resources :posts
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :username,uniqueness: true  
  validate :picture_size
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, password_length: 4..4

  def email_required?
    false
  end
  def email_changed?
    false
  end
  private
   def picture_size
    picture.size > 5.megabytes
  end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(params[:post].permit(:user_id, :post_id, :belo, :content))
    unless @post.save
      flash[:danger] = "文字を入力してください"
    end

    redirect_to user_path(@user)

  end
 

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def edit
    
  end

  def update
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.update(params[:post].permit(:user_id, :post_id, :belo, :content))
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    flash[:success] = "削除しました"
    redirect_to user_path(@user)
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!, only: [:edit, :update]
   before_action :correct_user,   only: [:edit, :update]
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(params[:user].permit(:username, :userdes, :usertxt, :picture))
    redirect_to root_path
  end

private
 def correct_user
  @user = User.find(params[:id])
  redirect_to root_path unless @user == current_user
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav>
    <ul class="global-nav">
      <div class="logo">
        <li><%= link_to 'Deai',root_path %></li>
      </div>
     <div class="menu">
      <li><%= link_to "TopPage",root_path %></li>
       <% if user_signed_in? %>
        <li><%= link_to " Sigh Out ",destroy_user_session_path, method: :delete %></li>
       <% else %>
       <li><%= link_to "Log In",new_user_session_path %></li>
      <% end %>
      </div>
    </ul>
  </nav>
</header>
<div class="wrap">
<div class="era">
  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert") %>
 </div>
  <% end %>
<%= yield %>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for ([@user, @user.posts.build]) do |f| %>
  <div class="field">
    <%= f.text_area :belo, placeholder: " 所属" %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "プロフィール" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<h3><%= post.belo %></h3>
<h3><%= post.content %></h3>
<% if  current_user == post.user %>
<div class="cd"><%= link_to '削除', [post.user, post], method: :delete, class: "buttn", date:{confirm: 'Are you sure'} %></div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :userdes%>
  <%= f.text_field :userdes, class: 'form-control' %>

  <%= f.label :usertxt%>
  <%= f.text_field :usertxt, class: 'form-control' %>

  <%= f.submit "編集", class: "btn btn-primary" %>
  <span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/edit.html.erb
<%= render "users/form" %>

app/views/users/index.html.erb
<h1>Usersindex</h1>
<div class="post_wrapper">
  <% @users.each do |user| %>
  <div class="post_box">
    <h3 class="title"><%= link_to user.username, user %></h3>
  <% end %>
 </div>

app/views/users/show.html.erb
<h1>Usersshow</h1>
<h3>  名前：<%= @user.username %></h3>
<h3>所属：<%= @user.userdes %></h3>
<h3>自己紹介：<%= @user.usertxt %></h3>
<%= image_tag @user.picture.url if @user.picture? %>
<% if  @user == current_user  %>
  <%= link_to "編集", edit_user_path(current_user) %>
<% end %>
<%= render @user.posts %>
<%= render "posts/form" %>